export const menuItems = [
  { href: "/", label: "Home" },
  { href: "/products", label: "Menu" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
  { href: "/faq", label: "FAQ" },
];

export const allProduct = [
  {
    id: "1",
    name: "Jollof Rice",
    description: "Spicy and flavorful rice dish",
    price: 12.99,
    category: "Main Dishes",
    image: "/foods/Jollof.jpg",
    rating: 4.5,
    reviews: [],
  },
  {
    id: "2",
    name: "Egusi Soup",
    description: "Rich soup with ground melon seeds",
    price: 14.99,
    category: "Soups",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.2,
    reviews: [],
  },
  {
    id: "3",
    name: "Puff Puff",
    description: "Sweet, deep-fried dough balls",
    price: 6.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "4",
    name: "Suya",
    description: "Spicy grilled meat skewers",
    price: 10.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    reviews: [],
  },
  {
    id: "5",
    name: "Moi Moi",
    description: "Steamed bean pudding",
    price: 8.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    reviews: [],
  },
  {
    id: "6",
    name: "Chin Chin",
    description: "Crunchy, sweet fried snack",
    price: 5.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.3,
    reviews: [],
  },
  {
    id: "7",
    name: "Akara",
    description: "Deep-fried bean cakes",
    price: 7.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "8",
    name: "Efo Riro",
    description: "Rich vegetable soup",
    price: 13.99,
    category: "Soups",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.4,
    reviews: [],
  },
  {
    id: "9",
    name: "Dodo",
    description: "Fried plantains",
    price: 6.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.1,
    reviews: [],
  },
  {
    id: "10",
    name: "Fried Rice",
    description: "Tasty and flavorful fried rice dish with vegs",
    price: 12.99,
    category: "Main Dishes",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [],
  },
  {
    id: "12",
    name: "Jollof Pasta",
    description: "Spicy and flavorful spaghetti dish",
    price: 12.99,
    category: "Main Dishes",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.1,
    reviews: [],
  },
  {
    id: "13",
    name: "Ewa Agoyin",
    description: "Delicious soft beans",
    price: 12.99,
    category: "Main Dishes",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [],
  },
  {
    id: "14",
    name: "Banana Bread",
    description: "Tasty banana bread",
    price: 12.99,
    category: "Bread",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.2,
    reviews: [],
  },
  {
    id: "15",
    name: "Nutty bread",
    description: "Spicy and flavorful rice dish",
    price: 12.99,
    category: "Bread",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.0,
    reviews: [],
  },
  {
    id: "16",
    name: "Chocolate Bread",
    description: "Spicy and flavorful rice dish",
    price: 12.99,
    category: "Bread",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.2,
    reviews: [],
  },
  {
    id: "17",
    name: "Okro Soup",
    description: "Rich okra soup with assorted",
    price: 13.99,
    category: "Soups",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.1,
    reviews: [],
  },
  {
    id: "18",
    name: "Pineapple Zobo",
    description: "Rich okra soup with assorted",
    price: 13.99,
    category: "Drinks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [],
  },
  {
    id: "19",
    name: "Orange Zobo",
    description: "Rich okra soup with assorted",
    price: 13.99,
    category: "Drinks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [],
  },
];

export const popularProducts = [
  {
    id: "1",
    name: "Jollof Rice",
    description: "Spicy and flavorful rice dish",
    price: 12.99,
    category: "Main Dishes",
    image: "/foods/Jollof.jpg",
    rating: 4.5,
    reviews: [],
  },
  {
    id: "2",
    name: "Egusi Soup",
    description: "Rich soup with ground melon seeds",
    price: 14.99,
    category: "Soups",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.2,
    reviews: [],
  },
  {
    id: "3",
    name: "Puff Puff",
    description: "Sweet, deep-fried dough balls",
    price: 6.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "4",
    name: "Suya",
    description: "Spicy grilled meat skewers",
    price: 10.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    reviews: [],
  },
  {
    id: "5",
    name: "Moi Moi",
    description: "Steamed bean pudding",
    price: 8.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    reviews: [],
  },
  {
    id: "6",
    name: "Chin Chin",
    description: "Crunchy, sweet fried snack",
    price: 5.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.3,
    reviews: [],
  },
  {
    id: "7",
    name: "Akara",
    description: "Deep-fried bean cakes",
    price: 7.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "8",
    name: "Efo Riro",
    description: "Rich vegetable soup",
    price: 13.99,
    category: "Soups",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.4,
    reviews: [],
  },
  {
    id: "9",
    name: "Dodo",
    description: "Fried plantains",
    price: 6.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.1,
    reviews: [],
  },
  {
    id: "10",
    name: "Fried Rice",
    description: "Tasty and flavorful fried rice dish with vegs",
    price: 12.99,
    category: "Main Dishes",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [],
  },
];

export const testimonials = [
  {
    name: "Sarah M.",
    quote:
      "The jollof rice was absolutely delicious! It reminded me of my grandmother's cooking.",
  },
  {
    name: "David O.",
    quote:
      "I've never had Nigerian food before, but Villedishes made me fall in love with it. The puff puff is addictive!",
  },
];

export const taxRate = 5;
export const shippingFee = 10;

export const demoItems = [
  {
    name: "Jollof rice",
    quantity: 0,
    price: 0.0,
  },
  {
    name: "Suya",
    quantity: 0,
    price: 0.0,
  },
  {
    name: "Puff-puff",
    quantity: 0,
    price: 0.0,
  },
  {
    name: "Zobo",
    quantity: 0,
    price: 0.0,
  },
];
