export const menuItems = [
  { href: "/", label: "Home" },
  { href: "/products", label: "Menu" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
  { href: "/faq", label: "FAQ" },
];
export const adminMenuItems = [
  { href: "/admin/", label: "Dashboard" },
  { href: "/admin/products", label: "Products" },
  { href: "/admin/orders", label: "Order" },
  { href: "/admin/invoices", label: "Invoice" },
  { href: "/admin/dashboard", label: "Deets" },
];

export const allProduct = [
  {
    id: "1",
    name: "Jollof Rice",
    description: "Spicy and flavorful rice dish",
    price: 12.99,
    category: "Main Dishes",
    image: "/foods/Jollof.jpg",
    rating: 4.5,
    reviews: [],
  },
  {
    id: "2",
    name: "Egusi Soup",
    description: "Rich soup with ground melon seeds",
    price: 14.99,
    category: "Soups",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.2,
    reviews: [],
  },
  {
    id: "3",
    name: "Puff Puff",
    description: "Sweet, deep-fried dough balls",
    price: 6.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "4",
    name: "Suya",
    description: "Spicy grilled meat skewers",
    price: 10.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    reviews: [],
  },
  {
    id: "5",
    name: "Moi Moi",
    description: "Steamed bean pudding",
    price: 8.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    reviews: [],
  },
  {
    id: "6",
    name: "Chin Chin",
    description: "Crunchy, sweet fried snack",
    price: 5.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.3,
    reviews: [],
  },
  {
    id: "7",
    name: "Akara",
    description: "Deep-fried bean cakes",
    price: 7.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "8",
    name: "Efo Riro",
    description: "Rich vegetable soup",
    price: 13.99,
    category: "Soups",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.4,
    reviews: [],
  },
  {
    id: "9",
    name: "Dodo",
    description: "Fried plantains",
    price: 6.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.1,
    reviews: [],
  },
  {
    id: "10",
    name: "Fried Rice",
    description: "Tasty and flavorful fried rice dish with vegs",
    price: 12.99,
    category: "Main Dishes",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [],
  },
  {
    id: "12",
    name: "Jollof Pasta",
    description: "Spicy and flavorful spaghetti dish",
    price: 12.99,
    category: "Main Dishes",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.1,
    reviews: [],
  },
  {
    id: "13",
    name: "Ewa Agoyin",
    description: "Delicious soft beans",
    price: 12.99,
    category: "Main Dishes",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [],
  },
  {
    id: "14",
    name: "Banana Bread",
    description: "Tasty banana bread",
    price: 12.99,
    category: "Bread",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.2,
    reviews: [],
  },
  {
    id: "15",
    name: "Nutty bread",
    description: "Spicy and flavorful rice dish",
    price: 12.99,
    category: "Bread",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.0,
    reviews: [],
  },
  {
    id: "16",
    name: "Chocolate Bread",
    description: "Spicy and flavorful rice dish",
    price: 12.99,
    category: "Bread",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.2,
    reviews: [],
  },
  {
    id: "17",
    name: "Okro Soup",
    description: "Rich okra soup with assorted",
    price: 13.99,
    category: "Soups",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.1,
    reviews: [],
  },
  {
    id: "18",
    name: "Pineapple Zobo",
    description: "Rich okra soup with assorted",
    price: 13.99,
    category: "Drinks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [],
  },
  {
    id: "19",
    name: "Orange Zobo",
    description: "Rich okra soup with assorted",
    price: 13.99,
    category: "Drinks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [],
  },
];

export const popularProducts = [
  {
    id: "1",
    name: "Jollof Rice",
    description: "Spicy and flavorful rice dish",
    price: 12.99,
    category: "Main Dishes",
    image: "/foods/Jollof.jpg",
    rating: 4.5,
    reviews: [],
  },
  {
    id: "2",
    name: "Egusi Soup",
    description: "Rich soup with ground melon seeds",
    price: 14.99,
    category: "Soups",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.2,
    reviews: [],
  },
  {
    id: "3",
    name: "Puff Puff",
    description: "Sweet, deep-fried dough balls",
    price: 6.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "4",
    name: "Suya",
    description: "Spicy grilled meat skewers",
    price: 10.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    reviews: [],
  },
  {
    id: "5",
    name: "Moi Moi",
    description: "Steamed bean pudding",
    price: 8.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    reviews: [],
  },
  {
    id: "6",
    name: "Chin Chin",
    description: "Crunchy, sweet fried snack",
    price: 5.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.3,
    reviews: [],
  },
  {
    id: "7",
    name: "Akara",
    description: "Deep-fried bean cakes",
    price: 7.99,
    category: "Snacks",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "8",
    name: "Efo Riro",
    description: "Rich vegetable soup",
    price: 13.99,
    category: "Soups",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.4,
    reviews: [],
  },
  {
    id: "9",
    name: "Dodo",
    description: "Fried plantains",
    price: 6.99,
    category: "Sides",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.1,
    reviews: [],
  },
  {
    id: "10",
    name: "Fried Rice",
    description: "Tasty and flavorful fried rice dish with vegs",
    price: 12.99,
    category: "Main Dishes",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [],
  },
];

export const testimonials = [
  {
    name: "Sarah M.",
    quote:
      "The jollof rice was absolutely delicious! It reminded me of my grandmother's cooking.",
  },
  {
    name: "David O.",
    quote:
      "I've never had Nigerian food before, but Villedishes made me fall in love with it. The puff puff is addictive!",
  },
];

export const taxRate = 5;
export const shippingFee = 10.0;

export const demoItems = [
  {
    name: "Jollof rice",
    quantity: 0,
    price: 0.0,
  },
  {
    name: "Suya",
    quantity: 0,
    price: 0.0,
  },
  {
    name: "Puff-puff",
    quantity: 0,
    price: 0.0,
  },
  {
    name: "Zobo",
    quantity: 0,
    price: 0.0,
  },
];

export const adminOverViewData = [
  {
    name: "Jan",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Feb",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Mar",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Apr",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "May",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Jun",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Jul",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Aug",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Sep",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Oct",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Nov",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Dec",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
];

export const adminRevenueGrowthData = [
  { name: "Jan", revenue: 4000 },
  { name: "Feb", revenue: 3000 },
  { name: "Mar", revenue: 5000 },
  { name: "Apr", revenue: 4500 },
  { name: "May", revenue: 6000 },
  { name: "Jun", revenue: 5500 },
  { name: "Jul", revenue: 7000 },
  { name: "Aug", revenue: 6500 },
  { name: "Sep", revenue: 8000 },
  { name: "Oct", revenue: 7500 },
  { name: "Nov", revenue: 9000 },
  { name: "Dec", revenue: 10000 },
];

export const adminProductPerformanceData = [
  { name: "Jollof Rice", value: 400 },
  { name: "Efo Riro", value: 300 },
  { name: "Puff-Puff", value: 300 },
  { name: "Banana Bread", value: 200 },
];

export const adminRecentOrders = [
  {
    customer: "Olivia Martin",
    order: "ORD-0005",
    orderDate: "2024-11-18",
    total: 199.0,
  },
  {
    customer: "Jackson Lee",
    order: "ORD-0004",
    orderDate: "2024-11-16",
    total: 19.99,
  },
  {
    customer: "Isabella Nguyen",
    order: "ORD-0003",
    orderDate: "2024-11-14",
    total: 21.99,
  },
  {
    customer: "William Kim",
    order: "ORD-0002",
    orderDate: "2024-11-12",
    total: 39.95,
  },
  {
    customer: "Sofia Davis",
    order: "ORD-0001",
    orderDate: "2024-11-10",
    total: 50.59,
  },
];

export const adminEmail = "villedishes@gmail.com";
export const testEmail = "oluwapelumi.ajuwon@gmail.com";
